SELECT 
    D.DEPARTMENT_NAME AS Departamento,
    J.JOB_TITLE AS Cargos,
    AVG(E.SALARY) AS Média_salarial
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.JOBS J
    ON E.JOB_ID = J.JOB_ID
GROUP BY D.DEPARTMENT_NAME, J.JOB_TITLE
ORDER BY Média_salarial DESC