    D.DEPARTMENT_NAME AS departamento,
    J.JOB_TITLE AS cargo,
    ROUND(AVG(E.SALARY),2) AS media_salarial
FROM HR.EMPLOYEES E
LEFT JOIN HR.DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HR.JOBS J 
    ON E.JOB_ID = J.JOB_ID
WHERE E.SALARY IS NOT NULL
GROUP BY D.DEPARTMENT_NAME, J.JOB_TITLE
ORDER BY media_salarial DESC;
