SELECT 
    D.DEPARTMENT_NAME AS Departamento,
    J.JOB_TITLE AS Cargos,
    E.SALARY AS Salario
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.JOBS J
    ON E.JOB_ID = J.JOB_ID
WHERE E.SALARY IS NOT NULL
ORDER BY Salario DESC